server:
  port: 8887

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/asset_management
    username: postgres
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true